// platform-ui/src/components/CodeEditorAndPreview.tsx
import React, { useState } from 'react';
import { SandpackProvider, SandpackLayout, SandpackCodeEditor, SandpackPreview } from '@codesandbox/sandpack-react';

interface CodePreviewProps {
  codeContent: string;
}

const CodeEditorAndPreview: React.FC<CodePreviewProps> = ({ codeContent }) => {
  const [showCode, setShowCode] = useState(false);
  const normalizedCodeContent = typeof codeContent === 'string' ? codeContent : '';

  // Files for Sandpack's virtual environment. This simulates the boilerplate's structure.
  const files = {
    '/src/app/page.tsx': { // This path mimics Next.js App Router's main page
      code: normalizedCodeContent, // Your AI-generated component goes here
      active: true, // This file is active in the editor
      hidden: false, // Not hidden from the editor view
    },
    '/src/app/layout.tsx': { // Minimal layout for Sandpack to understand Next.js App Router
      code: `
import React from 'react';
export const metadata = { title: 'Generated by AI' };
export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Assuming AI code in page.tsx uses Tailwind */}
      <body>{children}</body>
    </html>
  );
}
`,
      hidden: true,
    },
    '/src/app/globals.css': { // Basic global CSS for Tailwind
      code: `
@tailwind base;
@tailwind components;
@tailwind utilities;
body { margin: 0; font-family: sans-serif; }
`,
      hidden: true,
    },
    '/tailwind.config.ts': { // Tailwind config for Sandpack
      code: `
import type { Config } from 'tailwindcss'
const config: Config = {
  content: ['./src/app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      // Sandpack uses this config to compile Tailwind within the preview
    },
  },
  plugins: [],
}
export default config;
`,
      hidden: true,
    },
    '/next.config.mjs': { // Minimal next.config for Sandpack
      code: `
/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true };
export default nextConfig;
`,
      hidden: true,
    },
    '/package.json': { // Sandpack needs a package.json to know dependencies
      code: `
{
  "name": "generated-lp-sandpack",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@types/node": "20",
    "@types/react": "18",
    "@types/react-dom": "18",
    "autoprefixer": "10.4.18",
    "postcss": "8.4.35",
    "tailwindcss": "3.4.1",
    "typescript": "5"
  }
}
`,
      hidden: true,
    },
  };

  return (
    <div style={styles.container}>
      <h2 style={styles.title}>Generated Landing Page Code</h2>

      <div style={styles.controls}>
        {/* No download button here, as the full project is deployed */}
        <button onClick={() => setShowCode(!showCode)} style={styles.button}>
          {showCode ? 'Hide Code Editor' : 'Show Code Editor'}
        </button>
      </div>

      {/* Sandpack: The in-browser IDE for live preview */}
      <SandpackProvider template="nextjs" files={files} theme="dark"> {/* Use nextjs template */}
        <SandpackLayout style={styles.sandpackLayout}>
          {showCode ? (
            <SandpackCodeEditor style={styles.sandpackEditor} />
          ) : (
            <SandpackPreview style={styles.sandpackPreview} />
          )}
        </SandpackLayout>
      </SandpackProvider>
    </div>
  );
};

export default CodeEditorAndPreview;

// Basic inline styles for the platform UI's CodeEditorAndPreview component
const styles = {
  container: {
    width: '100%',
    backgroundColor: '#1f1f30',
    padding: '2rem',
    borderRadius: '12px',
    boxShadow: '0 8px 30px rgba(0, 0, 0, 0.4)',
    border: '1px solid #333355',
    marginTop: '2rem',
    display: 'flex' as const,
    flexDirection: 'column' as const,
    alignItems: 'center' as const,
  },
  title: {
    fontSize: '2rem',
    marginBottom: '1.5rem',
    color: '#f0f0f0',
    textAlign: 'center' as const,
  },
  controls: {
    display: 'flex' as const,
    gap: '1rem',
    marginBottom: '1.5rem',
    flexWrap: 'wrap' as const,
    justifyContent: 'center' as const,
  },
  button: {
    padding: '0.8rem 1.2rem',
    fontSize: '1rem',
    fontWeight: '700',
    fontFamily: "'Orbitron', sans-serif",
    backgroundColor: '#00CCFF',
    color: '#0d0d15',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease, transform 0.3s ease',
    boxShadow: '0 4px 15px rgba(0, 204, 255, 0.4)',
  },
  sandpackLayout: {
    width: '100%',
    height: '600px', // Fixed height for Sandpack preview
    border: '1px solid #333355',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 0 20px rgba(0, 204, 255, 0.2)',
  },
  sandpackEditor: {
    height: '100%',
    borderRadius: '0',
  },
  sandpackPreview: {
    height: '100%',
    borderRadius: '0',
    backgroundColor: '#fff', // Default background for preview iframe
  },
};